name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  shared-package:
    uses: ./.github/workflows/shared-ci.yml
    with:
      ref: ${{ github.sha }}

  mobile:
    needs: shared-package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - run: npm ci
      - run: npm run test --workspace=@huddlestat/mobile
      - run: npm run typecheck
